// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Models;

namespace Movies.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20230213191931_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Movies.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            Category = "Comedy/Drama",
                            Director = "Lulu Wang",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "The Farewell",
                            Year = 2019
                        },
                        new
                        {
                            ApplicationID = 2,
                            Category = "Romance",
                            Director = "Jon Turteltaub",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "While You Were Sleeping",
                            Year = 1995
                        },
                        new
                        {
                            ApplicationID = 3,
                            Category = "Drama/Romance",
                            Director = "Gus Van Sant",
                            Edited = true,
                            LentTo = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Good Will Hunting",
                            Year = 1997
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
